---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-balericacloudsec.com
  namespace: istio-ingress
spec:
  secretName: api-balericacloudsec.com-crt
  dnsNames:
    - app.balericacloudsec.com
  issuerRef:
    name: production-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io



    